FROM python:3.9

# 작업 디렉터리 설정
WORKDIR /app

# Python 의존성 파일 복사 및 설치
COPY ../../../../../../../../../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 전체 복사
COPY ../../../../../../../../.. .

# Flask 엔트리포인트 지정
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]